### PR TITLE
Fix SentinelOne limit error parsing

### LINKED ISSUE #128: [BUG] Limit is too large causing 400 errors on SentinelOne requests
## Describe the bug
With recent addition of limit param to specify a specific limit, this no causes SentinelOne to completely fail do to some endpoints having a max limit of 1000. With the limit being set to 20000 when not using PQ, this is not necessary due to fetching paginated data with dv results already which will fetch all returned results regardless of the limit.

## What side of Surveyor is impacted?
- [ ] Definition File
- [x] Code/Logic
- [ ] Other (please explain)

## What product is impacted?
- [ ] All Products
- [ ] Carbon Black Response
- [ ] Carbon Black Threat Hunter
- [ ] Defender for Endpoints
- [ ] SentinelOne
- [ ] Cortex
- [ ] Other

### What did you do?
What is the command line you're running that is causing the error? 
Command line 'surveyor --profile default --query 'SrcProcName = \"explorer.exe\"' s1 --creds <credfile> --dv'

### Expected behavior
No error should occur and query should execute for both PQ and DV

### PR DESCRIPTION
**Pull request by xC0uNt3r7hr34t**
removed 2000 limit option as this causes issues with multiple endpoints and is irrelevant with pagination.

resolves #128

### CODE REVIEW

**Comment by TreWilkinsRC** [comment]
Hey, this should be fixed in #125. Mind verifying?

**Comment by xC0uNt3r7hr34t** [comment]
Both PQ and DV have limitations for 1000. DV endpoint allows 20000 limit but the other endpoints hit by surveyor do not. It is recommended to use 1000 for everything.

**Comment by xC0uNt3r7hr34t** [comment]
the /accounts endpoint is what had a limit of 1000 that threw an error. if we want the ability to do a 20000 limit, it should only be used when hitting the /dv/events endpoint as this is where results are returned. if the limit isn't maximized the results will be returned via pagination.

**Comment by rc-abodkins** [comment]
@xC0uNt3r7hr34t with the merge of #125 - can you test again and see if the issue is fixed?

**Comment by xC0uNt3r7hr34t** [comment]
Issue is fixed via #125. Thanks

**Pull request closed without merging**
